### ISSUE TITLE
[Summer] Create a custom data type data structure and environment

### ISSUE THREAD

**Issue by jlvargasme** [jeannin/zelus#18]
The current implementation does not have an environment to hold custom data types defined in MARVLus.

Goal: Create a custom data type environment to hold the custom data type

The environment will be a map [string, custom type data structure], where "string" will be the custom data type alias, and the custom data type structure will be defined as below,

custom_t {
string base_type;
string reference_variable;
z3_expression Phi(reference_variable);
}

[Harder task] - Create a custom data type data structure and an environment to hold these data structures

**Comment by jchen-cs** [comment]
#52
