### ISSUE TITLE
[Summer] Optimize the data structure for storing refinement/non-refinement function

### ISSUE THREAD

**Issue by EasonZ2022** [jeannin/zelus#34]
```
| Efundecl of name * funexp
| Erefinementfundecl of name * funexp * exp
```

For now we store both refinement and non-refinement function in `Erefinementfundecl` which has one more field than `Efundecl.` 

We hope to finally utilize a pattern called `Efundecl` (which is the original name for function pattern) to hold all functions with as little modification as possible than the original data structure.

**Comment by jchen-cs** [comment]
#28 #29
