### ISSUE TITLE
[Summer] Parse new syntax for declaring refinement variables

### ISSUE THREAD

**Issue by EasonZ2022** [jeannin/zelus#43]
Old syntax of declaring refinement variables:
`let x : int{x > 0} = 1`
New syntax should be:
`let x : {v : int | v>0} = 1`

Instead of using the variable name directly in the refinement expression, we use an alias (e.g. `v` here) to refer to it.
So the parsing stage should carry additional information: the name of alias, to the verifying stage (in z3refinement.ml)

**Comment by jchen-cs** [comment]
#45 has tests reflecting the new syntax
