### ISSUE TITLE
Implement pair typing rules for new syntax

### ISSUE THREAD

**Issue by jlvargasme** [jeannin/zelus#51]
Also investigate how to write refinement types for each element
- using fst, snd keywords
- using name types, i.e let (x : {v : int | v > 100}, y : nat)

**Comment by jchen-cs** [comment]
Also implement dependent pairs:

- `(x, y):{(v:int, w:int) | v >= w}`

**Comment by jchen-cs** [comment]
Being worked on in branch `feature/pairs`

**Comment by jchen-cs** [comment]
#65
